WIP: indexアクションのspec
keito-sakakibara/el-training pull request #11
Opened 2021-02-09 10:20 UTC by keito-sakakibara

## やったこと

indexアクションのテスト
つまずいている点はTaskの要素数の取得がうまく行かない

## やらないこと

その他のアクションのテスト

## できるようになること（ユーザ目線）

indexアクションは有効である

## できなくなること（ユーザ目線）

。

## 動作確認
factories/tasks.rbでテストデータを作成。
```
factory :task1,class: Task do
    name {"task1"}
    detail {"task1です"}
  end
  factory :task2,class: Task do
    name {"task2"}
    detail {"task2です"}
```
今回はtask1,task2の二つ。

次にspec/controllers/tasks_controller_spec.rbで
```
it "taskのカウント数があっているか" do
      task1 = create(:task1)
      task2 = create(:task2)
      expect(Task.count).to eq(2)
end
```
こちらをテストするとcount数が予想の2ではなく3が返ってきてしまう。
createをbuildに変えたところ1が返ってくる。

2021-02-09 13:47 UTC, bst-n-sugita commented
PRに `wip` つけているとmergeできなくなる、と説明しましたが、その機能は別途プラグインをインストールしないとダメっぽいです、失礼しました😅
githubのデフォルト機能で同じことができるのでdraft PRを使ってみてください。（ `convert to draft` のところ）
<img src="https://user-images.githubusercontent.com/49134785/107372128-6dcdcd80-6b28-11eb-884d-387532e86a51.png" height="300">

2021-02-09 13:51 UTC, bst-n-sugita commented
あと `.DS_Store` みたいな余計なファイルはコミットしないようにしましょう！（必要であれば `.gitignore` に追記するもアリです）

2021-02-10 05:31 UTC, keito-sakakibara commented
> PRに `wip` つけているとmergeできなくなる、と説明しましたが、その機能は別途プラグインをインストールしないとダメっぽいです、失礼しました😅
> githubのデフォルト機能で同じことができるのでdraft PRを使ってみてください。（ `convert to draft` のところ）
> <img alt="" height="300" src="https://user-images.githubusercontent.com/49134785/107372128-6dcdcd80-6b28-11eb-884d-387532e86a51.png">

なぜかできない状態です、
**People who are already subscribed will not be unsubscribed.**
と表示されて押せないみたいです。

2021-02-10 06:09 UTC, bst-n-sugita commented
> なぜかできない状態です、

おや？
でもこのPRちゃんとdraftになってるから大丈夫そうですよ？
![image](https://user-images.githubusercontent.com/49134785/107472257-fb093480-6bb1-11eb-9946-aab1016400c3.png)

2021-02-10 08:03 UTC, keito-sakakibara reviewed
```suggestion
    context "タスクが存在しない時" do
      subject { -> {get task_path 5} }

      it { is_expected.to raise_error ActiveRecord::RecordNotFound }
    end
```

showアクションのタスクが存在しないページに飛んだ時のエラー処理の部分でraise が発生する場合は is_expectedは使用できないということでその解決策としてsubject で proc を返すようにするとうまく行くということで`subject { -> {get task_path 5} }`という風に書いたのですがうまく行かないです、コメントいただけるとありがたいです。

エラー内容
**Failure/Error: it { is_expected.to raise_error ActiveRecord::RecordNotFound }
       expected ActiveRecord::RecordNotFound but nothing was raised**

参考；https://secret-garden.hatenablog.com/entry/2016/09/01/000000

2021-02-10 11:35 UTC, keito-sakakibara commented
```suggestion
    context "パラメータが妥当な場合" do
      subject { put task_path task1, params: { task1: FactoryBot.attributes_for(:task1) } }

      it "リクエストが成功すること" do
        subject
        expect(response.status).to eq 302
      end
```
ここの部分でコメントいただきたいです。

**param is missing or the value is empty: task**
タスクの中身が空であるというエラーがですが
rails console で`actoryBot.attributes_for(:task1)`の中身を確認したところ
**{:name=>"task1", :detail=>"task1です"}**
このように表示されるので空ではないと思うのですが何かおかしいとろなどありますでしょうか。

2021-02-11 04:51 UTC, bst-n-sugita commented
https://github.com/keito-sakakibara/el-training/blob/controller_spec/app/controllers/tasks_controller.rb#L69
ここで `require(:task)` としているので、送るパラメータが以下のようなフォーマットになっていないと無視されます。
```
{
  task: {
    name: 'hoge',
    detail: 'fuga'
  }
}
```

2021-02-11 05:05 UTC, bst-n-sugita commented
また、テストデータの作り方についてですが、factoriesに定義すべきものは基本ひとつで、以下のように変数名や内容を変えたりすることで複数のデータを作りましょう。
https://github.com/keito-sakakibara/el-training/blob/request_spec_sugita/spec/controllers/tasks_controller_spec.rb#L17-L18
私が先日以下で書いていたことですね。
https://github.com/keito-sakakibara/el-training/pull/12/files#r572890824

現状榊原さんがやっているようにfactoriesに必要な数だけtask1やtask2を増やしていっていては、仮に100個のテストデータが必要になった時に大変ですよね。
デフォルトデータをfactoriesにひとつ定義しておいて、必要に応じて内容を上書きしたりして個別のテストデータを作っていくイメージです。

2021-02-11 05:38 UTC, keito-sakakibara commented
> また、テストデータの作り方についてですが、factoriesに定義すべきものは基本ひとつで、以下のように変数名や内容を変えたりすることで複数のデータを作りましょう。
> https://github.com/keito-sakakibara/el-training/blob/request_spec_sugita/spec/controllers/tasks_controller_spec.rb#L17-L18
> 私が先日以下で書いていたことですね。
> https://github.com/keito-sakakibara/el-training/pull/12/files#r572890824
> 
> 現状榊原さんがやっているようにfactoriesに必要な数だけtask1やtask2を増やしていっていては、仮に100個のテストデータが必要になった時に大変ですよね。
> デフォルトデータをfactoriesにひとつ定義しておいて、必要に応じて内容を上書きしたりして個別のテストデータを作っていくイメージです。

かしこまりました。
今回はtaskのみのテストデータを作成し、uppdateアクションなどで値を変更するときにはname:"sample",detail:"sample_detail"などとし内容を上書きし対応いたしました。

2021-02-11 07:35 UTC, bst-n-sugita requested changes
rubocop（gem）が追加されているのはなぜでしょうか？
rubocopの追加自体はとても良いことなのですが、このPRとは内容が全く違うので、できれば別PRで対応していただきたいです。また、その際に多分これまでのコードがrubocopに引っかかると思うので、同じPRで既存コードの修正対応もしてあると良いです。

また、`.gitignore` に追加されてはいるものの `.DS_Store` がpush内容に含まれていますので除外してください。（おそらくpush後に `.gitignore` に追加したのだと思うので、以前 `containers` で同じことをやってしまった時と同じような対処法になると思います。）

また、正式にレビューしてほしい段階になったらPRをdraftから通常に切り替え、タイトルの `WIP` も外してください。

最後に、PRのタイトルが実際の作業内容とマッチしていないので修正してみてください。

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/factories/tasks.rb
> +  factory :task,class: Task do
`class` の指定って必要なんですかね？
付与した意図をお聞きしたいです！

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +  describe '#show' do
可読性のため `describe` と `describe` の間には空行をはさんでください。

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +        expect(response.status).to eq 302
ステータスコード `302` はリダイレクトを意味していると思うので、「リクエストが成功すること」として別枠を設けるのではなく、80行目の「リダイレクトされること」の中に一緒に含める形で良いと思います。

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +    end
「パラメータが妥当な場合」とcontextを切っているので、「パラメータが妥当でない場合」もテストしてみてください。

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +        expect(response.status).to eq 302
`#create` と同様

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +    end
`#create` と同様に異常系contextも

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +      expect(response.status).to eq 302
`#create` と同様

2021-02-11 07:35 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +    it 'ユーザーが削除されること' do
ユーザー...？

2021-02-11 09:34 UTC, keito-sakakibara commented
> 1. rubocop（gem）が追加されているのはなぜでしょうか？
>    rubocopの追加自体はとても良いことなのですが、このPRとは内容が全く違うので、できれば別PRで対応していただきたいです。また、その際に多分これまでのコードがrubocopに引っかかると思うので、同じPRで既存コードの修正対応もしてあると良いです。
> 2. `.gitignore` に追加されてはいるものの `.DS_Store` がpush内容に含まれていますので除外してください。（おそらくpush後に `.gitignore` に追加したのだと思うので、以前 `containers` で同じことをやってしまった時と同じような対処法になると思います。）
> 3. 正式にレビューしてほしい段階になったらPRをdraftから通常に切り替え、タイトルの `WIP` も外してください。
> 4. PRのタイトルが実際の作業内容とマッチしていないので修正してみてください。

1.rubocopについては最初に導入したほうがいいという話があったのですが忘れていたためこのタイミングで導入してしまいました。masterから新しくブランチを切って導入し直したいと思います。
2.DS_Storeに関しましては削除いたしました。
3.4コメントいただいたところ修正でき次第WIP外しプルリクの内容も修正させていただきます。

2021-02-11 09:53 UTC, keito-sakakibara commented on spec/factories/tasks.rb
> +  factory :task,class: Task do
classは名前にモデル名以外をつけるときに使うものでした。
この場合はモデル名と同じ名前だったため必要ないです。

2021-02-11 13:58 UTC, keito-sakakibara commented on spec/controllers/tasks_controller_spec.rb
> +    end
すみませんこちら後ほどバリデーションなどを追加すると思ったのでこのような記述をしたのですが現在はcontextを切らずにバリデーションんを書いた際に追加したほうがよろしいでしょうか。

2021-02-12 06:25 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +    end
なるほどです！そういうことであれば今はこのままで大丈夫です！

2021-02-12 06:27 UTC, bst-n-sugita reviewed
以下が直ればLGTMです！

- rubocop絡みの記述がまだ残っている
  - `.rubocop.yml`
  - `.rubocop_todo.yml`
  - `Gemfile` からは消えたが `Gemfile.lock` にはrubocopの差分が出ている

2021-02-12 07:18 UTC, keito-sakakibara commented
> 以下が直ればLGTMです！
> 
> * rubocop絡みの記述がまだ残っている
>   
>   * `.rubocop.yml`
>   * `.rubocop_todo.yml`
>   * `Gemfile` からは消えたが `Gemfile.lock` にはrubocopの差分が出ている

変更内容pushしましたので確認いただけるとありがたいです。
https://github.com/keito-sakakibara/el-training/pull/13
またこちらでrubocopの導入を別ブランチで行ったのでお手際の際にご確認お願いいたします。

2021-02-12 07:57 UTC, bst-n-sugita reviewed
なんかまだGemfile.lockの差分でてますね。
1回削除して `bundle install` し直したら正しいやつが再生成されるかも？

2021-02-12 09:04 UTC, keito-sakakibara commented
> なんかまだGemfile.lockの差分でてますね。
> 1回削除して `bundle install` し直したら正しいやつが再生成されるかも？

bundle updateすることで解決できたかと思います！
確認お願いいたします。

2021-02-15 02:27 UTC, bst-n-sugita approved these changes
LGTM

2021-02-15 04:22 UTC, merged