Validatioステップ12: バリデーションを設定
keito-sakakibara/el-training pull request #15
Opened 2021-02-15 04:59 UTC by keito-sakakibara

## やったこと

app/models/task.rbに
`validates :name, presence: true`
を追加することでnameが空白であることを制限

## やらないこと
そのほかのバリデーション

## できるようになること（ユーザ目線）

## できなくなること（ユーザ目線）
nameを記述せずタスクを登録すること

* 何ができなくなるのか？

## 動作確認
spec/models/task_spec.rbにテストを記述し
**2 examples, 0 failures**

2021-02-15 05:03 UTC, keito-sakakibara commented
> ## やったこと
> app/models/task.rbに
> `validates :name, presence: true`
> を追加することでnameが空白であることを制限
> 
> ## やらないこと
> そのほかのバリデーション
> 
> ## できるようになること（ユーザ目線）
> ## できなくなること（ユーザ目線）
> nameを記述せずタスクを登録すること
> 
> * 何ができなくなるのか？
> 
> ## 動作確認
> spec/models/task_spec.rbにテストを記述し
> **2 examples, 0 failures**

## 質問
**合わせてDBの制約も設定するマイグレーションを作成しましょう**の部分なのですが`t.string :name, null: false`の様なものを新しく作成するという認識で間違い無いでしょうか。

2021-02-15 05:17 UTC, bst-n-sugita commented
> 合わせてDBの制約も設定するマイグレーションを作成しましょうの部分なのですがt.string :name, null: falseの様なものを新しく作成するという認識で間違い無いでしょうか。

既存のカラムに制約を追加するマイグレーションを作成しましょう、という意味だと思います。
既に `name` というカラムは存在していると思うので、今回でいうとそのカラムにnot null制約を追加しましょう、という意味ではないでしょうか。（現状だと `name` カラムはnull許容されているので）

2021-02-15 05:26 UTC, keito-sakakibara commented
> > 合わせてDBの制約も設定するマイグレーションを作成しましょうの部分なのですがt.string :name, null: falseの様なものを新しく作成するという認識で間違い無いでしょうか。
> 
> 既存のカラムに制約を追加するマイグレーションを作成しましょう、という意味だと思います。
> 既に `name` というカラムは存在していると思うので、今回でいうとそのカラムにnot null制約を追加しましょう、という意味ではないでしょうか。（現状だと `name` カラムはnull許容されているので）

```
class CreateTasks < ActiveRecord::Migration[5.2]
  def change
    create_table :tasks do |t|
      t.string :name, null: false
      t.text :detail

      t.timestamps
    end
  end
end
```
この様なマイグレーションファイルを作成するという認識なのですが違いますでしょうか

2021-02-15 05:36 UTC, bst-n-sugita commented
それだとまたtasksテーブルを作るマイグレーションファイルになってしまうので、こっちですね。
https://qiita.com/MOssan-32/items/89afc9e4375215f8b5d2

2021-02-15 05:50 UTC, keito-sakakibara commented
> それだとまたtasksテーブルを作るマイグレーションファイルになってしまうので、こっちですね。
> https://qiita.com/MOssan-32/items/89afc9e4375215f8b5d2

ありがとうございます！
参考になります！

2021-02-15 06:15 UTC, keito-sakakibara commented
DB制約のマイグレーションファイル作成いたしました。

2021-02-15 06:31 UTC, bst-n-sugita requested changes
1. conflictが起きていますので解消してください。
2. 最新のmasterを取り込んでrubocopを回してみてください。（修正の必要があれば要修正）
3. modelの他に、controllerの異常系テストも書いてみてください。

2021-02-15 06:31 UTC, bst-n-sugita commented on spec/models/task_spec.rb
> +  it "成功" do
正常系と異常系でcontextを切りましょう。
また、 `it` の説明は「〜であること」のようにもう少し丁寧に書いてください。
「成功」だけだと正直あまり意味が分かりませんし、何をテストしているのか分かりづらいです。

2021-02-15 07:28 UTC, keito-sakakibara commented on spec/models/task_spec.rb
> +  it "成功" do
すみません確認不足でした。
サンプルのまま変更せずpushしてしまいました。
変更しておきます

2021-02-15 07:29 UTC, keito-sakakibara commented
> 1. conflictが起きていますので解消してください。
> 2. 最新のmasterを取り込んでrubocopを回してみてください。（修正の必要があれば要修正）
> 3. modelの他に、controllerの異常系テストも書いてみてください。

修正出来次第pushいたします。

2021-02-15 09:58 UTC, keito-sakakibara commented
> > 1. conflictが起きていますので解消してください。
> > 2. 最新のmasterを取り込んでrubocopを回してみてください。（修正の必要があれば要修正）
> > 3. modelの他に、controllerの異常系テストも書いてみてください。
> 
> 修正出来次第pushいたします。

コンフリクトの改善
controllerの異常系のテストの追加
rubocopで**Style/FrozenStringLiteralComment**の部分で引っかかってたので
```
Style/FrozenStringLiteralComment:
  Enabled: false
```
を追加いたしました。
修正は全て完了いたしましたのでお手数ですがご確認お願いいたします。

2021-02-15 10:15 UTC, bst-n-sugita reviewed
コメントしました。
あと一歩です！

2021-02-15 10:15 UTC, bst-n-sugita commented on spec/models/task_spec.rb
> +end
可読性アップのため、modelのspecもcontrollerと同様に正常系と異常系でcontextを切っておいてください🙇‍♀️

2021-02-15 10:15 UTC, bst-n-sugita commented on .rubocop.yml
> +  Enabled: false
これは `false` にせず、全てのファイルに呪文のように `# frozen_string_literal: true` と書いておくのが一般的です。
理由や詳細はこちらを参考にしてみてください: https://teratail.com/questions/74592

2021-02-15 11:38 UTC, keito-sakakibara commented on spec/models/task_spec.rb
> +end
同じ様にcontextで正常と異常で分けました！

2021-02-15 11:39 UTC, keito-sakakibara commented on .rubocop.yml
> +  Enabled: false
ありがとうございます！
参考にいたします！

2021-02-15 12:19 UTC, keito-sakakibara commented
修正内容pushいたしました！

2021-02-16 00:56 UTC, bst-n-sugita approved these changes
LGTM

2021-02-16 02:19 UTC, merged