ステップ22: ログイン/ログアウト機能を実装しよう
keito-sakakibara/el-training pull request #25
Opened 2021-03-16 03:37 UTC by keito-sakakibara

## やったこと
・models/user.rbに`has_secure_password`を追加、password_digestカラムを追加。
→passwordとpassword_confirmationが使用可能
→authenticateメソッドが使えるようになる（引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド）

・sessionsコントローラーを作成しnew,create(login),destroy(logout)アクションを作成
・sessions_helper.rbにログイン、ログアウトのメソッドを記述
→logged_in?メソッドを使用しtasks/index.html.erbにてログインしている場合としていない場合で条件分岐
ログインしている場合：ログインしているユーザーのタスク一覧とログアウトのリンクを表示
ログインしていない場合：ログインを促すリンクのみを表示

## できるようになること（ユーザ目線）
自分以外タスク一覧を閲覧できなくなる

## できなくなること（ユーザ目線）
ログインしていないとタスク一覧画面にいけない

## 動作確認
ログインしていない状態でタスク一覧ページに飛べないかを確認（http://0.0.0.0/tasks/）

2021-03-16 05:42 UTC, bst-n-sugita requested changes
いくつかコメントしました。
加えて以下も対応をお願いします。

1. 「自分が作成したタスクだけを表示するようにしましょう」の実装が漏れています。（前ステップでTaskのcreate時にユーザーに紐づける処理も忘れていましたね💦）
2. `before_action` を使い、ログインしていない場合はtasks_controllerの全てのアクションを実行できないように制御を入れてください。（ログイン画面に飛ばす）
朝会で `tasks/index.html.erb` の表示を切り替える方法でOKとお伝えしてしまいましたが、この制御を入れると `tasks/index.html.erb` にもアクセスできなくなると思うので、やはりログイン画面に飛ばしましょう。次ステップでは、一般ユーザーのログイン画面のページ下部に「管理者はこちら」等のリンクを設置すれば良いかと思います。

2021-03-16 05:42 UTC, ta539tg70 commented on app/helpers/sessions_helper.rb
> +    !current_user.nil?
否定形はぱっと見だと人間の頭では理解しづらいので、よりスムーズに読めるよう `current_user.present?` にしておきましょう。

2021-03-16 05:42 UTC, ta539tg70 commented on app/helpers/sessions_helper.rb
> +  # @return [hash] session[:user_id]
`session[:user_id]` の実態は `user.id` だと思うので、返り値はhashじゃないですね。

2021-03-16 05:42 UTC, bst-n-sugita commented on app/helpers/sessions_helper.rb
> +    !current_user.nil?
と思ったけど、Viewから `current_user.present?` を呼び出せばログイン判定できますね。
ここでわざわざメソッド化する必要ありますかね？

2021-03-16 05:42 UTC, bst-n-sugita commented on app/controllers/sessions_controller.rb
> +      flash[:danger] = 'ログインに成功しました'
`flash[:success]` の間違いですかね。

2021-03-16 05:42 UTC, bst-n-sugita commented on app/helpers/sessions_helper.rb
> +  # @param [User] Objact フォームに送られたメールアドレスと一致するユーザー
typo: Objact→Object

2021-03-16 05:42 UTC, bst-n-sugita commented on app/helpers/sessions_helper.rb
> +  def log_in(user)
このメソッドの処理をそのままcontrollerの `create` アクションの中に直接書いたらまずいですか？
あえてhelperに切り出している理由があったらお聞きしたいです。
`log_in` メソッドの中身を知るためにわざわざわこのhelperを見ないといけないので、特になければcontrollerに直接書いた方が良いです。

2021-03-16 05:42 UTC, bst-n-sugita commented on app/helpers/sessions_helper.rb
> +  def log_out
`log_in` 同様、controllerに直接書くではダメか？

2021-03-16 05:42 UTC, bst-n-sugita commented on spec/requests/sessions_request_spec.rb
> +end
`create` と `destroy` のテストも書いてみてください！

2021-03-16 05:48 UTC, bst-n-sugita commented
> 次ステップでは、一般ユーザーのログイン画面のページ下部に「管理者はこちら」等のリンクを設置すれば良いかと思います。

朝会の話があったのでこう書いてしまいましたが、一般ユーザーも管理者ユーザーも共通のログイン画面からログインできる気がしました。（ログイン画面を分ける必要ってなにかあるんでしたっけ？）

2021-03-16 06:09 UTC, keito-sakakibara commented on app/helpers/sessions_helper.rb
> +    !current_user.nil?
こちらはログインしているかどうかを判別する上でわかりやすい名前の方がいいと思ったのでこの様にメソッドにしてしまいました、

2021-03-16 06:14 UTC, keito-sakakibara commented on app/controllers/sessions_controller.rb
> +      flash[:danger] = 'ログインに成功しました'
> 2. `before_action` を使い、ログインしていない場合はtasks_controllerの全てのアクションを実行できないように制御を入れてください。（ログイン画面に飛ばす）
>    朝会で `tasks/index.html.erb` の表示を切り替える方法でOKとお伝えしてしまいましたが、この制御を入れると `tasks/index.html.erb` にもアクセスできなくなると思うので、やはりログイン画面 `sessions/new.html.erb` に飛ばしましょう。次ステップでは、一般ユーザーのログイン画面のページ下部に「管理者はこちら」等のリンクを設置すれば良いかと思います。

かしこまりました！
その様に修正いたします！

2021-03-16 06:15 UTC, keito-sakakibara commented
> いくつかコメントしました。
> 加えて以下も対応をお願いします。
> 
> 1. 「自分が作成したタスクだけを表示するようにしましょう」の実装が漏れています。（前ステップでTaskのcreate時にユーザーに紐づける処理も忘れていましたね💦）

こちら
```
class AddUsersIdToTasks < ActiveRecord::Migration[5.2]
  def change
    add_reference :tasks, :user, foreign_key: true
  end
end
```
この実装でUserのidとTaskのuser_idが紐づいている状態じゃないんですかね、

2021-03-16 06:19 UTC, keito-sakakibara commented on app/helpers/sessions_helper.rb
> +  def log_out
問題ないと思います。
修正いたします。

2021-03-16 06:21 UTC, keito-sakakibara commented on app/helpers/sessions_helper.rb
> +  def log_in(user)
今後他のコントロラーなどで使う場面があった時便利だと思ってこの様な記述をしたのですがcreateに直接書いても問題ないのでその様に修正します！

2021-03-16 06:30 UTC, bst-n-sugita commented
> この実装でUserのidとTaskのuser_idが紐づいている状態じゃないんですかね、

DBの設計はそれで合っているのですが、 `tasks#create` でTaskを作成する際に `task.user_id` と `current_user.id` を紐づけて保存する処理を加えないと、実際には紐づいて保存されないですよね。
実際、現状で新規タスクを作成しようとするとUserがない旨のエラーが出て保存できないと思います。

2021-03-16 06:40 UTC, keito-sakakibara commented
> > この実装でUserのidとTaskのuser_idが紐づいている状態じゃないんですかね、
> 
> DBの設計はそれで合っているのですが、 `tasks#create` でTaskを作成する際に `task.user_id` と `current_user.id` を紐づけて保存する処理を加えないと、実際には紐づいて保存されないですよね。
> 実際、現状で新規タスクを作成しようとするとUserがない旨のエラーが出て保存できないと思います。
> そのmigrationはあくまでTaskとUserを紐づけて保存できるような器を作っただけの状態ですね。

わかりやすい説明ありがとうございます！
usersコントローラーのcreateアクションにてuser_idと現在のUserのidが一致する処理を書こうと思います

2021-03-16 08:56 UTC, keito-sakakibara commented
createとdestroyのspec時間かかりそうなのでその他の修正内容pushいたしました。
お手数ですがご確認お願いいたします。

2021-03-19 10:30 UTC, bst-n-sugita requested changes
コメントしました！

2021-03-19 10:30 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
sessions_helperに定義した `current_user` が使い回せるのではないですかね？

2021-03-19 10:30 UTC, bst-n-sugita commented on spec/requests/sessions_request_spec.rb
> +      expect(response).to redirect_to root_path
`session[:user_id]` が空になっていることもテストしてください。

2021-03-19 10:30 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +    @task = Task.find_by(user_id: @current_user.id)
34行目で `Task.new` したのを `find_by` で上書きしてしまっているので、このままだと正常にタスク作成できないと思います。（tasks_controller_specも落ちてませんかね？）
そうではなくて、34行目で `Task.new` した `@task` の `user_id` を `current_user.id` にする、という処理が必要です。

2021-03-19 10:30 UTC, bst-n-sugita commented on app/controllers/sessions_controller.rb
> +    redirect_to root_url
ここは `login_url` に飛ばす方が良いですね。
この実装だと、内部的には「ログアウト→ `tasks#index` にリダイレクト→ `before_action` によって弾かれてログインページへリダイレクト」という処理になってしまいます。
結果的にログインページにリダイレクトされるのは同じですが、「 `tasks#index` にリダイレクト」の挙動は完全に不要ですので省きましょう。

2021-03-19 10:30 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def logged_in_user
ユーザーをどうこうするメソッドではないので、 `require_login` などの名前にしておきましょう。

2021-03-19 10:30 UTC, bst-n-sugita commented on app/views/tasks/index.html.erb
> +<% if current_user.present? %>
`before_action` によってそもそもログインしていないとこのページに到達できなくなったので、この条件は不要になりましたね。

2021-03-19 10:30 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +    @task = Task.find_by(user_id: @current_user.id)
上記とは別に、 `before_action` を入れたことによって全てのテスト前に「ユーザーがログインしていること」が前提条件となったため、tasks_controller_specのテストが全部落ちている可能性がありますので確認してみてください。
`before` を使って、まずログインする、という記述をしてやると回避できると思います。
参考: https://qiita.com/k_momotani/items/f91252c92b18624e9ee4

2021-03-19 14:08 UTC, keito-sakakibara commented on app/controllers/sessions_controller.rb
> +    redirect_to root_url
かしこまりました
soec の方も修正いたしました

2021-03-19 14:09 UTC, keito-sakakibara commented on app/controllers/tasks_controller.rb
> +    @task = Task.find_by(user_id: @current_user.id)
かしこまりました。
ログインの記述にてこずってしまっているため終わり次第pushします！

2021-03-23 01:18 UTC, ta539tg70 requested changes
いくつかコメントしました。

また、こちらのコメント https://github.com/keito-sakakibara/el-training/pull/25#pullrequestreview-612852057 でも書いていますが、
> 「自分が作成したタスクだけを表示するようにしましょう」の実装が漏れています

indexアクションで `@tasks` を取得する際に `user_id` で絞り込む処理の追加が必要になります。

2021-03-23 01:18 UTC, ta539tg70 commented on app/controllers/tasks_controller.rb
> +    params.require(:task).permit(:name, :detail, :deadline_date, :status_id, :priority_id, :user_id)
`user_id` は特に受け付ける必要がないはずです。

2021-03-23 01:18 UTC, ta539tg70 commented on app/controllers/tasks_controller.rb
> +    @task.user_id = @current_user.id
33行目を削除して、ここをいきなり `@task.user_id = current_user.id` とすると動かないでしょうか？

2021-03-23 01:18 UTC, ta539tg70 commented on spec/controllers/tasks_controller_spec.rb
> +      let!(:task) { create(:task, user: create(:user, id: 1)) }
この辺りって何をやっているのでしょうか。

以下でUserを作っていて、
https://github.com/keito-sakakibara/el-training/blob/user_login/spec/controllers/tasks_controller_spec.rb#L6
そのUserでログインしていますよね。
https://github.com/keito-sakakibara/el-training/blob/user_login/spec/controllers/tasks_controller_spec.rb#L7-L10

なのにここでまた別のUserを作ってTaskに紐づけている...？

2021-03-23 01:18 UTC, ta539tg70 commented on spec/controllers/tasks_controller_spec.rb
> +      let!(:task) { create(:task, user: create(:user, id: 1)) }
その他のアクションも同様

2021-03-23 01:18 UTC, ta539tg70 commented on spec/controllers/tasks_controller_spec.rb
> +    let!(:task) { create(:task, status: create(:status, :todo), priority: create(:priority), user_id: user.id) }
これは正しいと思います。
以下で作ったUserに紐づけていますよね？
https://github.com/keito-sakakibara/el-training/blob/user_login/spec/controllers/tasks_controller_spec.rb#L6

2021-03-23 01:18 UTC, ta539tg70 commented on spec/controllers/tasks_controller_spec.rb
> +      let(:user) { create(:user) }
これはなんのため？

2021-03-23 01:18 UTC, ta539tg70 commented on spec/controllers/tasks_controller_spec.rb
> +                                                                       status_id: status.id, priority_id: priority.id, user_id: user.id) }
update時にViewから `user_id` は渡してないはずなので、specでも不要では？

2021-03-23 01:29 UTC, keito-sakakibara commented on app/controllers/tasks_controller.rb
> +    @task.user_id = @current_user.id
こちらで動くと思います！
その様に修正しておきます。

2021-03-23 01:32 UTC, keito-sakakibara commented on spec/controllers/tasks_controller_spec.rb
> +      let!(:task) { create(:task, user: create(:user, id: 1)) }
すみません。
こちら以下で作成する前の処理が残ってしまっていました。
Userの作成は以下のみですので修正しておきます。
https://github.com/keito-sakakibara/el-training/blob/user_login/spec/controllers/tasks_controller_spec.rb#L6

2021-03-23 01:33 UTC, keito-sakakibara commented on spec/controllers/tasks_controller_spec.rb
> +    let!(:task) { create(:task, status: create(:status, :todo), priority: create(:priority), user_id: user.id) }
その様になっています。

2021-03-23 01:48 UTC, keito-sakakibara commented
> いくつかコメントしました。
> 
> また、こちらのコメント [#25 (review)](https://github.com/keito-sakakibara/el-training/pull/25#pullrequestreview-612852057) でも書いていますが、
> 
> > 「自分が作成したタスクだけを表示するようにしましょう」の実装が漏れています
> 
> indexアクションで `@tasks` を取得する際に `user_id` で絞り込む処理の追加が必要になります。

こちら以下の様に記述することでuser_idとsession[:user_id]が一致するもののみ取り出しその後ソートなどの処理を追加する形で実装いたしました
`@tasks = Task.find_by(user_id: session[:user_id])`

2021-03-23 02:12 UTC, bst-n-sugita requested changes

2021-03-23 02:12 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +    @tasks = Task.find_by(user_id: session[:user_id])
`find_by` だと1件しか取得できないですし、これだとその次の `Task.all.order(created_at: :desc)` で上書きされてしまうため、意味がありません。
最初に `Task.all` しているところを `all` ではなく `where` で `user_id` で絞り込むように変更すれば良いと思います。また、その際に `current_user.id` が使えます。

2021-03-23 02:12 UTC, bst-n-sugita commented on spec/controllers/tasks_controller_spec.rb
> +      let!(:task) { create(:task, user: create(:user, id: 1)) }
んーーー？
`let!(:task) { create(:task, user: user) }` ではないですか？
なぜ新しいUserをcreateして紐づけているんでしょうか。
editとdestroyも同様

2021-03-23 02:23 UTC, keito-sakakibara commented on app/controllers/tasks_controller.rb
> +    @tasks = Task.find_by(user_id: session[:user_id])
以下に修正いたしました。
`@tasks = Task.where(user_id: current_user.id).order(created_at: :desc)`

2021-03-23 02:31 UTC, bst-n-sugita approved these changes
LGTM

2021-03-23 02:40 UTC, merged