WIP : ステップ23: ユーザの管理画面を実装しよう
keito-sakakibara/el-training pull request #26
Opened 2021-03-23 03:54 UTC by keito-sakakibara

## やったこと
routes.rbに以下を追加しadmin/users_pathなどのルーティングを作成
```
namespace :admin do
    resources :users
  end
```
 `docker-compose run --rm app rails generate controller admin/users`を実行しadmin/usersコントローラー作成

## 詰まっている点
destroyやupdate部分での**"/admin/users/4"**の様な値を受け取りたいのですがなぜか**"/admin/users.4"**となってしまう。

2021-03-23 11:45 UTC, bst-n-sugita requested changes
いくつかコメントしました。
また、以下の実装が漏れていますので対応お願いします。
> ユーザを削除したら、そのユーザが抱えているタスクを削除するようにしてみましょう

2021-03-23 11:45 UTC, bst-n-sugita commented on app/views/admin/users/show.html.erb
> +<%= link_to '削除する', admin_users_path(@user), method: :delete, data:{ confirm: '本当に削除してよろしいですか？'}, class: 'btn btn-danger' %>
昼間の問題の名残があります。
×`admin_users_path`
○`admin_user_path`

2021-03-23 11:45 UTC, bst-n-sugita commented on app/controllers/admin/users_controller.rb
> +  def index
このアクションにもコメントを書いておいてください。

2021-03-23 11:45 UTC, bst-n-sugita commented on app/controllers/admin/users_controller.rb
> +  def show
これにもコメント追加

2021-03-23 11:46 UTC, bst-n-sugita commented
`Task.counter_culture_fix_counts` は私の手元でも問題ありませんでした🎉

2021-03-23 13:53 UTC, keito-sakakibara commented
> いくつかコメントしました。
> また、以下の実装が漏れていますので対応お願いします。
> 
> > ユーザを削除したら、そのユーザが抱えているタスクを削除するようにしてみましょう

修正内容pushいたしました！
お手隙の際に確認お願いいたします。

2021-03-24 07:52 UTC, bst-n-sugita requested changes
> ユーザを削除したら、そのユーザが抱えているタスクを削除するようにしてみましょう

こちらに対する修正見ました。
榊原さんの実装でもたしかに実現はできているのですが、Railsにはこれを実現するための標準機能としてモデルに `dependent` オプションというものがありますので、そちらを使った方法に変えておきましょう。（実務ではほぼ100%こちらを使います。）

・親レコードを削除したら子レコードも削除する
・子レコードが存在する親レコードを削除しようとしたら例外を発生させる

などなど、 `dependent` には色々なオプションが存在します。
これを機に色々ググってみてください！

2021-03-24 08:43 UTC, keito-sakakibara commented
> > ユーザを削除したら、そのユーザが抱えているタスクを削除するようにしてみましょう
> 
> こちらに対する修正見ました。
> 榊原さんの実装でもたしかに実現はできているのですが、Railsにはこれを実現するための標準機能としてモデルに `dependent` オプションというものが存在していますので、そちらを使った方法に変えておきましょう。（実務でもほぼ100%こちらを使います。）
> 
> ・親レコードを削除したら子レコードも削除する
> ・子レコードが存在する親レコードを削除しようとしたら例外を発生させる
> 
> などなど、 `dependent` には色々なオプションが存在します。
> これを機に色々ググってみてください！

今回はmodels/user.rbに`has_many :tasks, dependent: :destroy`を記述することで親モデルが削除されたら子モデルも削除されるような記述をしたのですがこちらで間違い無いでしょうか

2021-03-24 09:01 UTC, bst-n-sugita commented
合ってます！

2021-03-24 09:10 UTC, keito-sakakibara commented
> 合ってます！

こちらマージしてよろしいということでしょうか。

2021-03-24 09:39 UTC, bst-n-sugita commented
pushされてたんですね😅
見落としてました、失礼しました。

2021-03-24 09:39 UTC, bst-n-sugita approved these changes
LGTM

2021-03-24 13:48 UTC, merged