WIP:ユーザにロールを追加しよう
keito-sakakibara/el-training pull request #27
Opened 2021-03-25 05:30 UTC by keito-sakakibara

## やったこと
・is_adminカラムを追加しtrueなら管理者、falseなら一般ユーザーのようなロール分け

・以下のようなメソッドを作成しadmin/users_controllerのbefore_actionで実行し管理ユーザだけがユーザ管理画面にアクセスできるように
```
def admin_user
    redirect_to(root_path) unless current_user.is_admin?
 end
```

・ロールを選択はadmin/users/edit.html.erbにてフォームのセレクトタグを使用し実装

・ユーザーの削除制限はmodels/user.rbにて以下のメソッドをbefore_destroyで実行し実装
```
def leave_at_least_one_admin_user
    unless User.where(is_admin: true).count > 1
      errors.add(:is_admin, "管理者は最低1人必要です")
      throw(:abort)
    end
  end
```

## やらないこと
一般ユーザが管理画面にアクセスした場合、専用の例外を出してみましょう
→ステップ26にて実装

## できるようになること（ユーザ目線）
管理者権限を持ったユーザーのみ管理者ページに飛べる

## できなくなること（ユーザ目線）
管理者以外管理者ページに飛べない

## 詰まっている点
ユーザーの削除制限にて
models/user.rbのleave_at_least_one_admin_userメソッドにて`errors.add(:is_admin, "管理者は最低1人必要です")`を実装することでエラーの条件に当てはまる場合error文を追加し下記のコードをadmin/users/index.html.erbに記述することでエラー文を表示したいのですがエラー文が反映されない

```
<% if user.errors.any? %>
            <ul>
                <% user.errors.full_messages.each do |message| %>
                     <li><%= message %></li>
                <% end %>
            </ul>
   <% end %>
```

2021-03-25 10:23 UTC, bst-n-sugita commented
あれ、これ私に対する質問になってましたかね。気付くの遅れてすみません。
slackで一声かけていただけるとありがたいです🙇‍♀️

で、回答ですが、まずdestroyアクションで削除に失敗した時の分岐がないので、今だと成功しようがしまいがユーザー一覧にリダイレクトされてしまってるのかな。そうすると多分 `errors` の中身もリセットされてしまう気がします。
あともしかしたらindexだと `@users` をループで回した `user` の `errors` って取れないかも...？ちょっとこの辺自身ないですが。あまりに難しいようだったら削除はユーザー詳細or編集からしかできない仕様にしちゃってもいいかもしれないです。

controllerやviewにデバッグコードを仕込みまくって、何がどこまで通っているか、どこが原因なのかなどを確認する癖をつけましょう！
究極は各行に `pp 'a'` とか入れて実行してみて、もし `a` がログに表示されたら「この箇所はちゃんと通ってるんだな」とか、変数を `pp` してみて期待通りの値が出力されるかnilなのかとか、しらみつぶしに調べていくイメージです。

2021-03-25 11:38 UTC, keito-sakakibara commented
> あれ、これ私に対する質問になってましたかね。気付くの遅れてすみません。
> slackで一声かけていただけるとありがたいです🙇‍♀️
> 
> で、回答ですが、まずdestroyアクションで削除に失敗した時の分岐がないので、今だと成功しようがしまいがユーザー一覧にリダイレクトされてしまってるのかな。そうすると多分 `errors` の中身もリセットされてしまう気がします。
> あともしかしたらindexだと `@users` をループで回した `user` の `errors` って取れないかも...？ちょっとこの辺自身ないですが。あまりに難しいようだったら削除はユーザー詳細or編集からしかできない仕様にしちゃってもいいかもしれないです。
> 
> controllerやviewにデバッグコードを仕込みまくって、何がどこまで通っているか、どこが原因なのかなどを確認する癖をつけましょう！
> 究極は各行に `pp 'a'` とか入れて実行してみて、もし `a` がログに表示されたら「この箇所はちゃんと通ってるんだな」とか、変数を `pp` してみて期待通りの値が出力されるかnilなのかとか、しらみつぶしに調べていくイメージです。

すみません。何度もslackでメッセージ送るのは迷惑だと思ってこちらで質問してしましました。次回からprなど送った際はslackで一声おかけします！現状エラーメッセージの表示はコントローラのdestroyアクションで@user.destroyが失敗した場合にflashにてエラー文を返す方法しか思いつきませんでした、
またデバックにつきましてはコントローラではppにて確認していたのですがviewでは確認をしていなかったためこれから確認する癖をつけるようにします。

2021-03-25 11:45 UTC, bst-n-sugita commented
すぐに反応できない時もあるとは思いますが、slackしていただくのは大丈夫ですよ👍

`if @user.destroy else render xx` すれば、flashに入れなくてもrender先でerrorsの内容が取得できると思います！（flashメッセージとerrorsの中身は別物なので）

2021-03-25 11:52 UTC, bst-n-sugita commented
indexで管理者の削除エラーを出すのはもしかしたら難しいかもしれないので、まずはshow or editで削除しようとした際にエラーを出せるようにしてみると良いかと思います！

2021-03-26 03:08 UTC, bst-n-sugita reviewed
少しコメントしましたが概ね良いですね！
あとはspecをお願いします。

2021-03-26 03:08 UTC, ta539tg70 commented on app/views/admin/users/show.html.erb
> +            <% if @tasks %>
20行目で分岐されているので、ここの分岐は不要ですね。

2021-03-26 03:08 UTC, bst-n-sugita commented on app/views/admin/users/show.html.erb
> +<%= paginate @tasks if @tasks %>
20行目の `if @tasks` のブロックの中に移動させてしまえば良いと思います！

2021-03-30 04:06 UTC, bst-n-sugita requested changes
少しだけコメントしましたがほぼOKです！
spec良い感じです👍✨

2021-03-30 04:06 UTC, ta539tg70 commented on app/views/admin/users/show.html.erb
> +                <td>タスクがありません</td>
これは `else` の中に移動させないと。

2021-03-30 04:06 UTC, bst-n-sugita commented on spec/requests/admin/users_request_spec.rb
> +      it 'メールアドレスが更新されること' do
前項のコピペのままになっているので正しいものに修正お願いします。

2021-03-30 04:28 UTC, keito-sakakibara commented on spec/requests/admin/users_request_spec.rb
> +      it 'メールアドレスが更新されること' do
管理者権限の変更に修正いたしました。

2021-03-30 05:05 UTC, bst-n-sugita approved these changes
LGTMです！

2021-03-30 05:06 UTC, merged