ステップ7-1: タスクの一覧画面、詳細画面を作成及びrspecのインストール
keito-sakakibara/el-training pull request #5
Opened 2021-02-06 14:10 UTC by keito-sakakibara

`docker-compose run --rm app rails generate controller tasks`こちらのコードでtasksコントローラーを作成し今回は一覧と詳細だったのでindex,showアクションを作成。
`routes.rb`ではルートにindexアクションを指定し、これからCRUDということで７つのアクションを使うことが想定されるので`resources tasks`を実行

rspecではステップ１４を参考にしrspecを導入。
`spec/spec_helper.rb` 、 `spec/rails_helper.rb`共に作成を確認できたためpush

2021-02-07 04:24 UTC, bst-n-sugita requested changes
いくつかコメントしましたのでご確認ください。

2021-02-07 04:24 UTC, bst-n-sugita commented on Gemfile
> +  gem 'rspec-rails'
> 課題ステップ3rdフェーズ
> ステップ15: Factory botでテストオブジェクトを作成しよう
> factory_bot gemを :development, :test グループに追加しましょう
> buildし直してインストールしましょう
> 今まで作ったModelのFactory botを作ろう

こちらも今後テストを書いていただく際に必要になりますので、この段階で一緒にやってみてください！

2021-02-07 04:24 UTC, bst-n-sugita commented on app/views/tasks/index.html.erb
> +</ul>
ファイルの末尾には空行を入れておくのが正とされていますので、今から入れる習慣をつけておきましょう。
参考: https://teratail.com/questions/71778

2021-02-07 04:24 UTC, bst-n-sugita commented on app/views/tasks/show.html.erb
> +<%= link_to "一覧へ",tasks_path%>
同様に空行追加

2021-02-07 04:24 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  end
アクションとアクションの間には空行があると見やすいので入れておきましょう。
今後も可読性を考えながらコーディングしていけると良いですね。

2021-02-07 04:24 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def index
先日少しお話した「コメント」を書いてみていただきたいです！
ちょっと古いですが参考記事: https://morizyun.github.io/blog/yard-rails-ruby-gem-document-html/index.html
gemをインストールする必要はないので、上記の参考記事はコメントの書き方のサンプルとして見てもらえればと思います。

アクションやメソッド単位で以下が書いてあると好ましいです。
・対象のメソッドが行っている処理の概要
・引数を受け取るメソッドならば、どんな引数を受け取るのか
・返り値は何になるのか

実務ではこれだけシンプルなコードにコメントをつけることは少ないですが、今から慣れておくという意味で練習がてら書いてみてください！

2021-02-07 04:24 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def show
こちらにもコメント書いてみてください。

2021-02-07 13:25 UTC, bst-n-sugita requested changes
あと一歩かと思います！

2021-02-07 13:25 UTC, ta539tg70 commented on Gemfile
> +  # gem 'factory_bot'
不要な名残は削除しましょう。

2021-02-07 13:25 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def index
ちょっと分かりづらかったかもですが、イメージこんな感じです！
```ruby
# 全てのタスクを取得する
# @return [Array<Task>]
def index
  @tasks = Task.all
end
```
もし受け取る引数やパラメータがあるなら `@param` が追記される感じですね。

2021-02-07 13:25 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def show
`index` アクションを参考に修正してみてください！

2021-02-07 13:25 UTC, bst-n-sugita commented on config/application.rb
> +
謎の複数空行が...。

2021-02-07 13:25 UTC, bst-n-sugita commented on spec/factories/tasks.rb
> +end
こちらも空行追加ですね。
この赤丸マークで空行が欠けていることが分かります。
![image](https://user-images.githubusercontent.com/49134785/107147542-fc5c1680-6991-11eb-9f8b-8b26e1815880.png)

2021-02-07 13:25 UTC, bst-n-sugita commented on app/views/tasks/index.html.erb
> +</ul>
index＆show共にですが、あまりにもテンション上がらないので適当にCSS当ててみませんか？
課題ステップ3rdフェーズのステップ20の先取りですね。
「ステップ20でやるから今はこのままいきたい」ということであれば強要はしませんので大丈夫です。
ただ自分でローカル確認してる時にあまりにもシンプル過ぎる見た目でつまらなくないかなと思いまして...。

2021-02-07 13:25 UTC, bst-n-sugita commented on app/views/tasks/index.html.erb
> +      <%= link_to task.name, task %>
タスクがひとつもない時は「タスクがありません」と表示させたいですね！
画面設計でも一応そういう想定にしていたはずなので！

2021-02-07 15:46 UTC, keito-sakakibara commented on app/views/tasks/index.html.erb
> +</ul>
簡単ではありますがスタイル当てました！

2021-02-07 15:47 UTC, keito-sakakibara commented on app/views/tasks/index.html.erb
> +      <%= link_to task.name, task %>
```
<% if @tasks%>
        <%= link_to task.name, task, {class: "task"}%>
      <% else %>
        <p>タスクがありません</p>
 <%end%>
```
if文でタスクがある時とない時で表示変更いたしました！

2021-02-07 15:48 UTC, keito-sakakibara commented on config/application.rb
> +
空白何度も申し訳ございません。
気おつけます、、

2021-02-07 15:51 UTC, keito-sakakibara commented
コメントの追加と簡単なスタイル当てさせていただきました。
お手数ですがご確認お願いいたします。

2021-02-08 03:27 UTC, bst-n-sugita approved these changes
1点コメントしましたがapproveしておきます。
次のPRで一緒に直っていればOKなのでこれはmergeしちゃって大丈夫です。
今後アクションやメソッドを追加する度にコメントは書いていってください🙏

2021-02-08 03:27 UTC, bst-n-sugita commented on app/controllers/tasks_controller.rb
> +  def show
`[]` の中には型を書いておく感じです。
```
対象タスクを取得する
@param [Integer] タスクID
@return [Object<Task>]
```
細かくて申し訳ないですが、今後のためと思って...🙏

2021-02-08 15:17 UTC, merged